config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @post = Post.last
    @last_but_one_post = Post.last(2).first
    @last_but_two_post = Post.last(3).first
    @last_but_three_post = Post.last(4).first
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def posts
    @posts = Posts.order(created_at: :desc)
  end

  def index
    @posts = Post.all
  end

  def show
    @post
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post successfully created.'}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<section class="container-fluid px-0">
  <div class="row align-items-center">
    <div class="col-md-6">
      <div id="headingGroup" class="text-white text-center d-none d-md-block mt-5">
        <h1>LEGO<span>|</span>PROJECT</h1>
        <p class="lead px-5 text-white text-center">Welcome to our Lego project site! We'll be building a new lego project every week</p>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag 'lego_home_image.jpg', :class => "img-fluid" %>
    </div>
  </div>
</section>

<section class="container-fluid px-0">
  <div class="row align-items-center content">
    <div class="col-md-6 order-2 order-md-1">
      <% if Post.last %>
        <%= image_tag @post.image, :class => "img-fluid" %>
      <% else %>
        <%= image_tag 'gumball.png', :class => "img-fluid" %>
      <% end %>
    </div>
    <div class="col-md-6 text-center order-1 order-md-2">
      <div class="row justify-content-center">
        <div class="col-10 col-lg-8 mb-5 mb-md-0">
          <% if Post.last %>
            <h2><%= link_to "#{@post.title}", @post %></h2>
            <%= image_tag 'lego_brick_icon.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white post_content"><%= @post.content %></p>
          <% else %>
            <h2>LEGO<span>|</span>PROJECT</h2>
            <%= image_tag 'lego_brick_icon.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, iste molestiae
                            beatae, maiores deserunt
                            in voluptatibus
                            aspernatur architecto excepturi delectus soluta? Ipsa, deleniti dolorem hic consequatur
                            repellat eveniet quidem
                            voluptate necessitatibus dolorum delectus minus vitae, ut, veritatis sint ipsum magnam
                            autem nam ex deserunt debitis
                            eaque ratione! Nobis, quidem assumenda.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row align-items-center content">
    <div class="col-md-6 text-center">
      <div class="row justify-content-center">
        <div class="col-10 col-lg-8 mb-5 mb-md-0">
          <% if Post.all.length > 1 %>
            <h2><%= link_to "#{@last_but_one_post.title}", @last_but_one_post %></h2>
            <%= image_tag 'lego_brick_icon_2.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white post_content"><%= @last_but_one_post.content %></p>
          <% else %>
            <h2>LEGO<span>|</span>PROJECT</h2>
            <%= image_tag 'lego_brick_icon_2.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, iste molestiae
                            beatae, maiores deserunt
                            in voluptatibus
                            aspernatur architecto excepturi delectus soluta? Ipsa, deleniti dolorem hic consequatur
                            repellat eveniet quidem
                            voluptate necessitatibus dolorum delectus minus vitae, ut, veritatis sint ipsum magnam
                            autem nam ex deserunt debitis
                            eaque ratione! Nobis, quidem assumenda.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <% if Post.all.length > 1 %>
        <%= image_tag @last_but_one_post.image, :class => "img-fluid" %>
      <% else %>
        <%= image_tag 'gumball.png', :class => "img-fluid" %>
      <% end %>
    </div>
  </div>
  <div class="row align-items-center content">
    <div class="col-md-6 order-2 order-md-1">
      <% if Post.all.length > 2 %>
        <%= image_tag @last_but_two_post.image, :class => "img-fluid" %>
      <% else %>
        <%= image_tag 'gumball.png', :class => "img-fluid" %>
      <% end %>
    </div>
    <div class="col-md-6 text-center order-1 order-md-2">
      <div class="row justify-content-center">
        <div class="col-10 col-lg-8 mb-5 mb-md-0">
          <% if Post.all.length > 2 %>
            <h2><%= link_to "#{@last_but_two_post.title}", @last_but_two_post %></h2>
            <%= image_tag 'lego_brick_icon_3.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white post_content"><%= @last_but_two_post.content %></p>
          <% else %>
            <h2><a href="#">LEGO<span>|</span>PROJECT</a></h2>
            <%= image_tag 'lego_brick_icon_3.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white">Check back later when we post more Lego projects!</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row align-items-center content">
    <div class="col-md-6 text-center">
      <div class="row justify-content-center">
        <div class="col-10 col-lg-8 mb-5 mb-md-0">
          <% if Post.all.length > 3 %>
            <h2><%= link_to "#{@last_but_three_post.title}", @last_but_three_post %></h2>
            <%= image_tag 'lego_brick_icon_4.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white post_content"><%= @last_but_three_post.content %></p>
          <% else %>
            <h2><a href="#">LEGO<span>|</span>PROJECT</a></h2>
            <%= image_tag 'lego_brick_icon_4.png', :class => "d-none d-lg-inline" %>
            <p class="lead text-white">Lego is fun! Guess what we're building next!</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <% if Post.all.length > 3 %>
        <%= image_tag @last_but_three_post.image, :class => "img-fluid" %>
      <% else %>
        <%= image_tag 'gumball.png', :class => "img-fluid" %>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<nav id="mainNavbar" class="navbar navbar-dark navbar-expand-md py-0 fixed-top">
  <%= link_to 'LEGO|PROJECT', root_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navLinks" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navLinks">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'HOME', root_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'ALL PROJECTS', posts_path, :class => 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'NEW POST', new_post_path, :class => 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'SIGN IN', user_session_path, :class => 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LEGO|PROJECT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400,700" rel="stylesheet">
  </head>

  <body>
    <%= render :partial => 'layouts/navbar' %>
    <%= yield %>
    <%= render :partial => 'layouts/footer' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <script>
      $(function () {
        $(document).scroll(function () {
          var $nav = $("#mainNavbar");
            $nav.toggleClass("scrolled", $(this).scrollTop() > $nav.height());
        });
      });
    </script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, multipart: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prevented this post from being saved:</h2>
      <ul>
        <%= post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, :required => true, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", :class => "btn btn-dark" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% obj.each do |post| %>
  <li class="list-group-item">
    <h4><%= link_to post.title, post_path(post) %></h4>
    <small><%= post.created_at.strftime("%d/%m/%Y") %></small>
  </li>
<% end %>

app/views/posts/edit.html.erb
<div class="container-fluid pt-5">
  <h2>Edit Post</h2>
  <div class="row">
    <div class="col-sm-7 col-md-6 col-lg-5 col-xl-4">
      <%= render 'form', post: @post %>
      <%= link_to 'Back', posts_path, :class => "btn btn-light mt-2" %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid pt-5">
  <h2>All Projects</h2>
  <div class="row">
    <div class="col-sm-7 col-md-6 col-lg-5 col-xl-4">
      <div class="list-group">
        <%= render 'post', obj: @posts.order(created_at: :desc) %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid pt-5">
  <h2>New Post</h2>
  <div class="row">
    <div class="col-sm-7 col-md-6 col-lg-5 col-xl-4">
      <%= render 'form', post: @post %>
      <%= link_to 'Back', posts_path, :class => "btn btn-light mt-2" %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row align-items-center content">
  <div class="col-md-6 order-2 order-md-1">
    <%= image_tag @post.image, :class => "img-fluid" %>
  </div>
  <div class="col-md-6 text-center order-1 order-md-2">
    <div class="row justify-content-center">
      <div class="col-10 col-lg-8 mb-5 mb-md-0">
        <h2><%= link_to "#{@post.title}", @post %></h2>
        <%= image_tag 'lego_brick_icon.png', :class => "d-none d-lg-inline" %>
        <p class="lead text-white post_content"><%= @post.content %></p>
        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_post_path(@post), :class => "text-white" %> | 
          <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, :class => "text-white" %> | 
        <% end %>
        <%= link_to 'Back', posts_path, :class => "text-white" %>
      </div>
    </div>
  </div>
</div>